import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://devmgm.ibos.io/');
  await page.getByRole('textbox', { name: 'Enter your mobile no' }).click();
  await page.getByRole('textbox', { name: 'Enter your mobile no' }).fill('01796662');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('123456');
  await page.getByRole('button', { name: 'LOG IN' }).click();
  await page.getByText('Account').first().click();
   await page.goto('https://devmgm.ibos.io/accounts/businessTransaction');
  await page.getByRole('button', { name: 'Journal' }).click();
  await page.getByRole('textbox', { name: 'Narration' }).click();
  await page.getByRole('textbox', { name: 'Narration' }).fill('testby sam');
  await page.locator('#chartOfAccount > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: '- Cash in hand' }).click();
  await page.locator('.css-uevkuo-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: 'Debit' }).click();
  await page.getByPlaceholder('Amount').click();
  await page.getByPlaceholder('Amount').fill('101');
  await page.getByRole('button', { name: 'Add List' }).click();
  await page.getByRole('columnheader', { name: 'Customer/Supplier/Employee' }).click();
  await page.locator('#chartOfAccount').getByTestId('ArrowDropDownIcon').click();
  await page.getByRole('option', { name: '555555 - Inventory' }).click();
  await page.locator('.css-uevkuo-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: 'Credit' }).click();
  await page.getByRole('button', { name: 'Add List' }).click();
  await page.getByRole('button', { name: 'SAVE' }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('textbox', { name: 'Narration' }).click();
  await page.getByRole('textbox', { name: 'Narration' }).fill('testbysam');
  await page.locator('#chartOfAccount > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: '- Cash in hand' }).click();
  await page.getByPlaceholder('Amount').click();
  await page.locator('#debitOrCredit > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.locator('#debitOrCredit > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByPlaceholder('Amount').click();
  await page.getByPlaceholder('Amount').fill('102');
  await page.getByRole('button', { name: 'Add List' }).click();
  await page.locator('#chartOfAccount > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: '555555 - Inventory' }).click();
  await page.locator('.css-uevkuo-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: 'Credit' }).click();
  await page.getByRole('button', { name: 'Add List' }).click();
  await page.getByRole('button', { name: 'SAVE' }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('textbox', { name: 'Narration' }).click();
  await page.getByRole('textbox', { name: 'Narration' }).fill('testbySam');
  await page.locator('#chartOfAccount > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: '- Prepayments' }).click();
  await page.locator('#debitOrCredit > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: 'Debit' }).click();
  await page.locator('#debitOrCredit').getByTestId('ArrowDropDownIcon').click();
  await page.locator('#debitOrCredit #react-select-mgm-input').fill('');
  await page.getByRole('option', { name: 'Debit' }).click();
  await page.getByPlaceholder('Amount').fill('102');
  await page.getByRole('button', { name: 'Add List' }).click();
  await page.locator('#chartOfAccount > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: '- Cash in hand' }).click();
  await page.locator('div').filter({ hasText: /^Debit Or Credit$/ }).nth(4).click();
  await page.getByRole('option', { name: 'Credit' }).click();
  await page.getByRole('button', { name: 'Add List' }).click();
  await page.getByRole('button', { name: 'SAVE' }).click();
  await page.waitForTimeout(2000);
  await page.locator('#chartOfAccount > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: '- Accounts payable' }).click();
  await page.getByRole('textbox', { name: 'Narration' }).click();
  await page.locator('#chartOfAccount #react-select-mgm-input').fill('t');
  await page.getByRole('textbox', { name: 'Narration' }).fill('est');
  await page.getByRole('textbox', { name: 'Narration' }).click();
  await page.locator('div').filter({ hasText: /^Date$/ }).first().dblclick();
  await page.locator('div').filter({ hasText: /^Date$/ }).first().click();
  await page.getByRole('textbox', { name: 'Narration' }).click();
  await page.getByRole('textbox', { name: 'Narration' }).fill('testbysam');
  await page.locator('#debitOrCredit > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: 'Debit' }).click();
  await page.locator('.css-i8r28j').click();
  await page.getByRole('option', { name: 'Bhai Bhai Milk Supplier' }).click();
  await page.getByPlaceholder('Amount').fill('102');
  await page.getByRole('button', { name: 'Add List' }).click();
  await page.locator('#chartOfAccount > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: '- Cash in hand' }).click();
  await page.getByRole('option', { name: '- Cash in hand' }).click();
  await page.getByRole('img', { name: 'demo' }).click();
  await page.getByRole('button', { name: 'Log Out' }).click();
});