import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://mgm.ibos.io/');
  await page.getByRole('textbox', { name: 'Enter your mobile no' }).click();
  await page.getByRole('textbox', { name: 'Enter your mobile no' }).fill('01974338899');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('123456');
  await page.getByRole('button', { name: 'LOG IN' }).click();
  await page.locator('div').filter({ hasText: /^Account$/ }).click();
  await page.getByRole('link', { name: 'Accounting Journal' }).click();
  await page.getByRole('button', { name: 'Journal' }).click();
  await page.getByRole('textbox', { name: 'Narration' }).click();
  await page.getByRole('textbox', { name: 'Narration' }).fill('automation test by samanta');
  await page.locator('#chartOfAccount > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: 'Inventory', exact: true }).click();
  await page.locator('.css-uevkuo-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: 'Debit' }).click();
  await page.getByPlaceholder('Amount').fill('20002');
  await page.getByRole('textbox', { name: 'Remarks' }).click();
  await page.getByRole('textbox', { name: 'Remarks' }).fill('x');
  await page.getByRole('button', { name: 'Add List' }).click();
  await page.locator('#chartOfAccount > .css-tmcups-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: '- Cash in hand' }).click();
  await page.locator('.css-uevkuo-control > .css-1ifxr7z > .css-18w4uv4').click();
  await page.getByRole('option', { name: 'Credit' }).click();
  await page.getByRole('textbox', { name: 'Remarks', exact: true }).click();
  await page.getByRole('textbox', { name: 'Remarks', exact: true }).fill('y');
  await page.getByRole('button', { name: 'Add List' }).click();
  await page.getByRole('button', { name: 'SAVE' }).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('tab', { name: 'Pending Voucher' }).click();
  await page.getByText('JV-M260600009').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('img', { name: 'demo' }).click();
  await page.getByRole('button', { name: 'Log Out' }).click();
});